# Generated by Django 5.0.6 on 2024-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_alter_admin_helath_csv_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolongued_decelerations', models.FloatField()),
                ('percentage_abnormal_long_term_variability', models.FloatField()),
                ('accelerations', models.FloatField()),
                ('abnormal_short_term_variability', models.FloatField()),
                ('severe_decelerations', models.FloatField()),
                ('histogram_variance', models.FloatField()),
                ('light_decelerations', models.FloatField()),
                ('histogram_min', models.FloatField()),
                ('uterine_contractions', models.FloatField()),
                ('mean_value_short_term_variability', models.FloatField()),
                ('histogram_mean', models.FloatField()),
                ('baseline_value', models.FloatField()),
                ('explanation_type', models.CharField(choices=[('lime', 'LIME'), ('shap', 'SHAP')], max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Admin_Helath_CSV',
            new_name='Admin_Health_CSV',
        ),
    ]
