# Generated by Django 5.0.6 on 2024-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_fetaldetail_rename_admin_helath_csv_admin_health_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Fetal_Health_CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(max_length=255, upload_to='csv_files/')),
                ('name', models.CharField(default='ndata.csv', editable=False, max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_Health_CSV',
        ),
    ]
